#spring.application.name=microservice-utils

#application.name: microservice-utils
#application.version: 1.0
#application.link: http://localhost:8082/

#server:
#  port: 8082
#  servlet:
#    context-path: /utils/api/v1

spring:
  application:
    name: microservice-utils
  config:
    import: optional:configserver:http://localhost:8888

#eureka:
#  client:
#   service-url:
#      defaultZone: ${EUREKA_SERVER}
    #register-with-eureka: false
    #fetch-registry: false
