application.name: microservice-issue
application.version: 1.0
application.link: http://localhost:8085/

server:
  port: 8085
  servlet:
    context-path: /issue/api/v1

spring:
  application:
    name: microservice-issue
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL} #jdbc:mysql://localhost:3306/student_db
    username: ${DB_USER} #root
    password: ${DB_PASS} #dabel
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #${EUREKA_SERVER}
    #register-with-eureka: false
    #fetch-registry: false
