#spring.application.name=microservice-utils
application:
  name: microservice-chat
  version: 1.0
  link: http://localhost:8086/

# SERVER CONFIGURATION
server:
  port: 8086
  #servlet:
  #  context-path: /utils/api/v1
# SPRING APPLICATION CONFIGURATION
spring:
  application:
    name: microservice-chat
# EUREKA CONFIGURATION
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #${EUREKA_SERVER}
    #register-with-eureka: false
    #fetch-registry: false
