#spring.application.name=microservice-utils

application:
  name: microservice-utils
  version: 1.0
  link: http://localhost:8082/

# SERVER CONFIGURATION
server:
  port: 8082
  servlet:
    context-path: /utils/api/v1

# SPRING APPLICATION CONFIGURATION
spring:
  application:
    name: microservice-utils
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    username: dabel6061@gmail.com
    password: rydzkcnykgegvomb

# EUREKA CONFIGURATION
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #${EUREKA_SERVER}
    #register-with-eureka: false
    #fetch-registry: false
