#spring.application.name=microservice-eureka
server:
  port: 8761

application.name: microservice-eureka
application.version: 1.0
application.link: http://localhost:8761/

spring:
  application:
    name: microservice-eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

