application.name: microservice-librarian
application.version: 1.0
application.link: http://localhost:8084/

server:
  port: 8084
  servlet:
    context-path: /librarian/api/v1

spring:
  application:
    name: microservice-librarian
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_librarian
    username: root
    password: dabel
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #${EUREKA_SERVER}
    #register-with-eureka: false
    #fetch-registry: false
